<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="co.edu.uts.inmobiliaria.model.AdminUser,co.edu.uts.inmobiliaria.model.CatalogItem,co.edu.uts.inmobiliaria.model.AuditEntry,java.util.List,java.sql.Timestamp,java.time.format.DateTimeFormatter,java.util.Locale" %>
<%!
    private String fechaHoraLegible(Timestamp fecha) {
        if (fecha == null) return "-";
        return DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy, hh:mm a", new Locale("es", "CO"))
                .format(fecha.toLocalDateTime());
    }
%>
<%
    List<AdminUser> usuarios = (List<AdminUser>) request.getAttribute("usuarios");
    List<CatalogItem> ciudades = (List<CatalogItem>) request.getAttribute("ciudades");
    List<CatalogItem> tipos = (List<CatalogItem>) request.getAttribute("tipos");
    List<CatalogItem> caracteristicas = (List<CatalogItem>) request.getAttribute("caracteristicas");
    List<AuditEntry> auditoria = (List<AuditEntry>) request.getAttribute("auditoria");
%>
<%@ include file="/WEB-INF/jspf/cabecera.jspf" %>
<%@ include file="/WEB-INF/jspf/navegacion.jspf" %>
<main class="container py-5">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><span class="section-kicker">Solo administrador</span><h1 class="fw-bold mb-1">Panel administrativo</h1><p class="text-secondary mb-0">Gestiona usuarios, roles y catálogos generales del sistema.</p></div><div class="d-flex flex-wrap gap-2 align-items-center"><a class="btn btn-outline-dark" href="<%= request.getContextPath() %>/app/reportes">Ver reportes</a><% if (Boolean.TRUE.equals(request.getAttribute("sincronizacionAutomatica"))) { %><span class="badge rounded-pill text-bg-success">Sincronización automática activa · cada <%= request.getAttribute("sincronizacionIntervalo") %> s</span><% } %></div></div>
    <% if ("ok".equals(request.getParameter("rol"))) { %><div class="alert alert-success">El rol fue actualizado correctamente.</div><% } %>
    <% if ("ok".equals(request.getParameter("estado"))) { %><div class="alert alert-success">El estado de la cuenta fue actualizado.</div><% } %>
    <% if ("ok".equals(request.getParameter("catalogo"))) { %><div class="alert alert-success">El elemento fue agregado al catálogo.</div><% } %>
    <% if ("ok".equals(request.getParameter("creado"))) { %><div class="alert alert-success">El usuario fue creado correctamente.</div><% } %>
    <% if (request.getAttribute("errorAdmin") != null) { %><div class="alert alert-danger"><%= request.getAttribute("errorAdmin") %></div><% } %>
    <div class="card operation-card shadow-sm mb-4"><div class="card-body p-4"><div class="form-heading mb-3"><span class="form-heading-icon">+</span><div><h2 class="h5 fw-bold mb-1">Registrar usuario</h2><p class="small text-secondary mb-0">Crea cuentas con el rol correspondiente desde este panel.</p></div></div><form action="<%= request.getContextPath() %>/app/admin" method="post" class="row g-3"><input type="hidden" name="accion" value="crearUsuario"><div class="col-md-3"><label class="form-label" for="nuevoNombres">Nombres</label><input class="form-control" id="nuevoNombres" name="nombres" placeholder="Ej. Ana María" required></div><div class="col-md-3"><label class="form-label" for="nuevoApellidos">Apellidos</label><input class="form-control" id="nuevoApellidos" name="apellidos" placeholder="Ej. Gómez Pérez" required></div><div class="col-md-2"><label class="form-label" for="nuevoDocumento">Documento</label><input class="form-control" id="nuevoDocumento" name="documento" placeholder="Ej. 1098765432" required></div><div class="col-md-4"><label class="form-label" for="nuevoCorreo">Correo</label><input class="form-control" id="nuevoCorreo" name="correo" type="email" placeholder="usuario@correo.com" required></div><div class="col-md-4"><label class="form-label" for="nuevoPassword">Contraseña</label><input class="form-control" id="nuevoPassword" name="password" type="password" minlength="8" placeholder="Mínimo 8 caracteres" required></div><div class="col-md-4"><label class="form-label" for="nuevoRol">Rol</label><select class="form-select" id="nuevoRol" name="rol" required><option value="CLIENTE">Cliente</option><option value="INMOBILIARIA">Inmobiliaria</option><option value="ADMINISTRADOR">Administrador</option><option value="VISITANTE">Visitante</option></select></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-accent w-100" type="submit">Registrar usuario</button></div></form></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 fw-bold mb-1">Usuarios y roles</h2><p class="small text-secondary mb-0">Asigna un rol y activa o inactiva cuentas.</p></div><span class="badge text-bg-light"><%= usuarios == null ? 0 : usuarios.size() %> usuarios</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Usuario</th><th>Correo</th><th>Rol actual</th><th>Cuenta</th><th>Acciones</th></tr></thead><tbody><% if (usuarios != null) { for (AdminUser usuario : usuarios) { %><tr><td><strong><%= usuario.getName() %></strong></td><td><%= usuario.getEmail() %></td><td><span class="badge text-bg-light"><%= usuario.getRoles() %></span></td><td><span class="status-badge <%= usuario.isActive() ? "status-aprobado" : "status-rechazado" %>"><%= usuario.isActive() ? "ACTIVA" : "INACTIVA" %></span></td><td><div class="d-flex flex-wrap gap-2"><form action="<%= request.getContextPath() %>/app/admin" method="post" class="d-flex gap-1"><input type="hidden" name="accion" value="rol"><input type="hidden" name="idUsuario" value="<%= usuario.getId() %>"><select class="form-select form-select-sm" name="rol"><option>ADMINISTRADOR</option><option>INMOBILIARIA</option><option>CLIENTE</option><option>VISITANTE</option></select><button class="btn btn-sm btn-outline-primary" type="submit">Asignar</button></form><form action="<%= request.getContextPath() %>/app/admin" method="post"><input type="hidden" name="accion" value="estado"><input type="hidden" name="idUsuario" value="<%= usuario.getId() %>"><button class="btn btn-sm btn-outline-secondary" type="submit"><%= usuario.isActive() ? "Inactivar" : "Activar" %></button></form></div></td></tr><% } } else { %><tr><td colspan="5">No fue posible cargar usuarios.</td></tr><% } %></tbody></table></div></div></div>
    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 fw-bold mb-1">Auditoría reciente</h2><p class="small text-secondary mb-0">Últimas acciones registradas en el sistema.</p></div><span class="badge text-bg-light"><%= auditoria == null ? 0 : auditoria.size() %> eventos</span></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>Detalle</th></tr></thead><tbody><% if (auditoria != null && !auditoria.isEmpty()) { for (AuditEntry evento : auditoria) { %><tr><td class="text-nowrap"><%= fechaHoraLegible(evento.getCreatedAt()) %></td><td><%= evento.getActor() %></td><td><span class="badge text-bg-light"><%= evento.getAction() %></span></td><td><%= evento.getEntity() %><%= evento.getEntityId() == null ? "" : " #" + evento.getEntityId() %></td><td class="text-secondary"><%= evento.getDetail() == null ? "-" : evento.getDetail() %></td></tr><% } } else { %><tr><td colspan="5" class="text-secondary">Todavía no hay eventos de auditoría.</td></tr><% } %></tbody></table></div></div></div>
    <div class="row g-4"><div class="col-lg-5"><div class="card operation-card h-100 shadow-sm"><div class="card-body p-4"><div class="form-heading mb-3"><span class="form-heading-icon">+</span><div><h2 class="h5 fw-bold mb-1">Parametrizar catálogos</h2><p class="small text-secondary mb-0">Agrega opciones que usarán los formularios.</p></div></div><form action="<%= request.getContextPath() %>/app/admin" method="post" class="row g-3"><input type="hidden" name="accion" value="catalogo"><div class="col-12"><label class="form-label" for="catalogo">Catálogo</label><select class="form-select" id="catalogo" name="catalogo"><option value="ciudad">Ciudad</option><option value="tipo">Tipo de propiedad</option><option value="caracteristica">Característica</option></select></div><div class="col-12"><label class="form-label" for="nombre">Nombre</label><input class="form-control" id="nombre" name="nombre" placeholder="Ej. Lebrija" required></div><div class="col-12"><button class="btn btn-accent w-100" type="submit">Agregar opción</button></div></form></div></div></div><div class="col-lg-7"><div class="card report-card h-100 shadow-sm"><div class="card-body p-4"><h2 class="h5 fw-bold">Catálogos actuales</h2><div class="gold-line mb-3"></div><h3 class="small text-uppercase text-secondary">Ciudades</h3><div class="catalog-chips mb-3"><% if (ciudades != null) { for (CatalogItem item : ciudades) { %><span><%= item.getName() %></span><% } } %></div><h3 class="small text-uppercase text-secondary">Tipos de propiedad</h3><div class="catalog-chips mb-3"><% if (tipos != null) { for (CatalogItem item : tipos) { %><span><%= item.getName() %></span><% } } %></div><h3 class="small text-uppercase text-secondary">Características</h3><div class="catalog-chips"><% if (caracteristicas != null) { for (CatalogItem item : caracteristicas) { %><span><%= item.getName() %></span><% } } %></div></div></div></div></div>
</main>
<%@ include file="/WEB-INF/jspf/pie.jspf" %>
