<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="co.edu.uts.inmobiliaria.model.Property,co.edu.uts.inmobiliaria.model.Appointment,co.edu.uts.inmobiliaria.model.PropertyRequest,co.edu.uts.inmobiliaria.model.RequestDocument,java.util.List,java.sql.Timestamp,java.time.format.DateTimeFormatter,java.util.Locale" %>
<%!
    private String fechaHoraLegible(Timestamp fecha) {
        if (fecha == null) return "-";
        return DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy, hh:mm a", new Locale("es", "CO"))
                .format(fecha.toLocalDateTime());
    }

    private Property buscarPropiedad(List<Property> propiedades, String id) {
        if (propiedades == null || id == null || id.isEmpty()) return null;
        for (Property propiedad : propiedades) {
            if (String.valueOf(propiedad.getId()).equals(id)) return propiedad;
        }
        return null;
    }
%>
<%
    List<Property> propiedades = (List<Property>) request.getAttribute("propiedades");
    List<Appointment> citas = (List<Appointment>) request.getAttribute("citas");
    List<PropertyRequest> solicitudes = (List<PropertyRequest>) request.getAttribute("solicitudes");
    List<RequestDocument> documentos = (List<RequestDocument>) request.getAttribute("documentos");
    boolean esGestor = Boolean.TRUE.equals(request.getAttribute("esGestor"));
    String errorOperaciones = (String) request.getAttribute("errorOperaciones");
    String propiedadSeleccionada = (String) request.getAttribute("propiedadSeleccionada");
    Property propiedadPreseleccionada = buscarPropiedad(propiedades, propiedadSeleccionada);
%>
<%@ include file="/WEB-INF/jspf/cabecera.jspf" %>
<%@ include file="/WEB-INF/jspf/navegacion.jspf" %>
<main class="container py-5">
    <div class="mb-4"><span class="section-kicker">Sprint 3 · Operación</span><h1 class="fw-bold mb-1">Citas y solicitudes</h1><p class="text-secondary mb-0"><%= esGestor ? "Administra las solicitudes y agenda de todos los clientes." : "Agenda visitas y envía solicitudes sobre las propiedades disponibles." %></p></div>
    <% if (request.getAttribute("mensajeOperaciones") != null) { %><div class="alert alert-success"><%= request.getAttribute("mensajeOperaciones") %></div><% } %>
    <% if (request.getAttribute("errorOperaciones") != null) { %><div class="alert alert-danger"><%= request.getAttribute("errorOperaciones") %></div><% } %>
    <% if (errorOperaciones != null) { %><div class="alert alert-danger"><%= errorOperaciones %></div><% } %>

    <div class="row g-4 mb-5">
        <div class="col-lg-6" id="form-cita"><div class="card operation-card h-100 shadow-sm"><div class="card-body p-4"><div class="form-heading mb-3"><span class="form-heading-icon">◷</span><div><h2 class="h5 fw-bold mb-1">Agendar una visita</h2><p class="text-secondary small mb-0">Selecciona una propiedad y un horario.</p></div></div><form action="<%= request.getContextPath() %>/app/operaciones.jsp" method="post" class="row g-3"><input type="hidden" name="accion" value="crearCita"><div class="col-12"><label class="form-label" for="propiedadCita">Propiedad</label><select class="form-select" id="propiedadCita" name="idPropiedad" required><option value="">Selecciona una propiedad</option><% if (propiedades != null) { for (Property propiedad : propiedades) { %><option value="<%= propiedad.getId() %>" <%= String.valueOf(propiedad.getId()).equals(propiedadSeleccionada) ? "selected" : "" %>><%= propiedad.getTitle() %> · <%= propiedad.getCity() %></option><% } } %></select></div><div class="col-12"><% if (propiedadPreseleccionada != null) { String imagen = propiedadPreseleccionada.getImageUrl() == null ? request.getContextPath() + "/assets/images/altaltium-logo.png" : propiedadPreseleccionada.getImageUrl(); %><div class="property-selection-preview"><img src="<%= imagen %>" alt="<%= propiedadPreseleccionada.getTitle() %>"><div><small>Propiedad seleccionada</small><strong><%= propiedadPreseleccionada.getTitle() %></strong></div></div><% } else { %><small class="text-secondary">La imagen aparecerá al abrir este formulario desde una propiedad.</small><% } %></div><div class="col-md-6"><label class="form-label" for="fechaHora">Fecha y hora</label><input class="form-control" id="fechaHora" name="fechaHora" type="datetime-local" required></div><div class="col-md-6"><label class="form-label" for="observaciones">Observaciones</label><input class="form-control" id="observaciones" name="observaciones" maxlength="255" placeholder="Ej. Visita en la tarde"></div><div class="col-12"><button class="btn btn-accent w-100" type="submit">Solicitar cita</button></div></form></div></div></div>
        <div class="col-lg-6" id="form-solicitud"><div class="card operation-card h-100 shadow-sm"><div class="card-body p-4"><div class="form-heading mb-3"><span class="form-heading-icon">✦</span><div><h2 class="h5 fw-bold mb-1">Radicar solicitud</h2><p class="text-secondary small mb-0">Indica si deseas comprar o arrendar.</p></div></div><form action="<%= request.getContextPath() %>/app/operaciones.jsp" method="post" class="row g-3"><input type="hidden" name="accion" value="crearSolicitud"><div class="col-12"><label class="form-label" for="propiedadSolicitud">Propiedad</label><select class="form-select" id="propiedadSolicitud" name="idPropiedad" required><option value="">Selecciona una propiedad</option><% if (propiedades != null) { for (Property propiedad : propiedades) { %><option value="<%= propiedad.getId() %>" <%= String.valueOf(propiedad.getId()).equals(propiedadSeleccionada) ? "selected" : "" %>><%= propiedad.getTitle() %> · <%= propiedad.getOperation() %></option><% } } %></select></div><div class="col-12"><% if (propiedadPreseleccionada != null) { String imagen = propiedadPreseleccionada.getImageUrl() == null ? request.getContextPath() + "/assets/images/altaltium-logo.png" : propiedadPreseleccionada.getImageUrl(); %><div class="property-selection-preview"><img src="<%= imagen %>" alt="<%= propiedadPreseleccionada.getTitle() %>"><div><small>Propiedad seleccionada</small><strong><%= propiedadPreseleccionada.getTitle() %></strong></div></div><% } else { %><small class="text-secondary">La imagen aparecerá al abrir este formulario desde una propiedad.</small><% } %></div><div class="col-12"><label class="form-label" for="tipoOperacion">Tipo de operación</label><select class="form-select" id="tipoOperacion" name="tipoOperacion" required><option value="">Selecciona una opción</option><option value="COMPRA">Compra</option><option value="ARRIENDO">Arriendo</option></select></div><div class="col-12"><button class="btn btn-accent w-100" type="submit">Radicar solicitud</button></div></form></div></div></div>
    </div>

    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 fw-bold mb-0">Citas registradas</h2><span class="badge text-bg-light"><%= citas == null ? 0 : citas.size() %></span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Propiedad</th><th>Cliente</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody><% if (citas != null && !citas.isEmpty()) { for (Appointment cita : citas) { %><tr><td><strong><%= cita.getPropertyTitle() %></strong><% if (cita.getObservations() != null) { %><br><small class="text-secondary"><%= cita.getObservations() %></small><% } %></td><td><%= cita.getClientName() %></td><td class="text-nowrap"><%= fechaHoraLegible(cita.getDateTime()) %></td><td><span class="status-badge status-<%= cita.getStatus().toLowerCase() %>"><%= cita.getStatus() %></span></td><td><% if (esGestor && ("PENDIENTE".equals(cita.getStatus()) || "CONFIRMADA".equals(cita.getStatus()))) { %><form action="<%= request.getContextPath() %>/app/operaciones.jsp" method="post" class="d-flex gap-1"><input type="hidden" name="accion" value="estadoCita"><input type="hidden" name="idCita" value="<%= cita.getId() %>"><select class="form-select form-select-sm" name="estado"><% if ("PENDIENTE".equals(cita.getStatus())) { %><option value="CONFIRMADA">CONFIRMADA</option><option value="CANCELADA">CANCELADA</option><% } else { %><option value="ATENDIDA">ATENDIDA</option><option value="CANCELADA">CANCELADA</option><% } %></select><button class="btn btn-sm btn-accent" type="submit">Guardar</button></form><% } else if (esGestor) { %><span class="text-secondary small">Sin transiciones disponibles</span><% } %></td></tr><% } } else { %><tr><td colspan="5" class="text-secondary">Aún no hay citas registradas.</td></tr><% } %></tbody></table></div></div></div>

    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 fw-bold mb-0">Solicitudes</h2><span class="badge text-bg-light"><%= solicitudes == null ? 0 : solicitudes.size() %></span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Propiedad</th><th>Cliente</th><th>Operación</th><th>Estado</th><th>Creada</th><th>Documentos / acciones</th></tr></thead><tbody><% if (solicitudes != null && !solicitudes.isEmpty()) { for (PropertyRequest solicitud : solicitudes) { %><tr><td><strong><%= solicitud.getPropertyTitle() %></strong></td><td><%= solicitud.getClientName() %></td><td><span class="badge text-bg-light"><%= solicitud.getOperationType() %></span></td><td><span class="status-badge status-<%= solicitud.getStatus().toLowerCase() %>"><%= solicitud.getStatus() %></span></td><td class="text-nowrap"><%= fechaHoraLegible(solicitud.getCreatedAt()) %></td><td><% if (!esGestor) { %><form action="<%= request.getContextPath() %>/app/documentos.jsp" method="post" enctype="multipart/form-data" class="document-upload-form"><input type="hidden" name="idSolicitud" value="<%= solicitud.getId() %>"><input class="form-control form-control-sm" type="file" name="archivo" accept=".pdf,.jpg,.jpeg,.png" required><button class="btn btn-sm btn-accent" type="submit">Cargar</button></form><% } %><% if (esGestor && ("RADICADA".equals(solicitud.getStatus()) || "EN_REVISION".equals(solicitud.getStatus()))) { %><form action="<%= request.getContextPath() %>/app/operaciones.jsp" method="post" class="d-flex gap-1"><input type="hidden" name="accion" value="estadoSolicitud"><input type="hidden" name="idSolicitud" value="<%= solicitud.getId() %>"><select class="form-select form-select-sm" name="estado"><% if ("RADICADA".equals(solicitud.getStatus())) { %><option value="EN_REVISION">EN_REVISION</option><option value="RECHAZADA">RECHAZADA</option><% } else { %><option value="APROBADA">APROBADA</option><option value="RECHAZADA">RECHAZADA</option><% } %></select><button class="btn btn-sm btn-accent" type="submit">Guardar</button></form><% } else if (esGestor) { %><span class="text-secondary small">Sin transiciones disponibles</span><% } %></td></tr><% } } else { %><tr><td colspan="6" class="text-secondary">Aún no hay solicitudes registradas.</td></tr><% } %></tbody></table></div></div></div>

    <div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 fw-bold mb-0">Documentos cargados</h2><span class="badge text-bg-light"><%= documentos == null ? 0 : documentos.size() %></span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Solicitud</th><th>Archivo</th><th>Estado</th><th></th></tr></thead><tbody><% if (documentos != null && !documentos.isEmpty()) { for (RequestDocument documento : documentos) { %><tr><td><%= documento.getPropertyTitle() %></td><td><a href="<%= documento.getFileUrl() %>" target="_blank" rel="noopener"><%= documento.getFileName() %></a></td><td><span class="status-badge status-<%= documento.getStatus().toLowerCase() %>"><%= documento.getStatus() %></span></td><td><% if (esGestor) { %><form action="<%= request.getContextPath() %>/app/documentos.jsp" method="post" class="d-flex gap-1"><input type="hidden" name="accion" value="estadoDocumento"><input type="hidden" name="idDocumento" value="<%= documento.getId() %>"><select class="form-select form-select-sm" name="estado"><option <%= "PENDIENTE".equals(documento.getStatus()) ? "selected" : "" %>>PENDIENTE</option><option <%= "APROBADO".equals(documento.getStatus()) ? "selected" : "" %>>APROBADO</option><option <%= "RECHAZADO".equals(documento.getStatus()) ? "selected" : "" %>>RECHAZADO</option></select><button class="btn btn-sm btn-outline-primary" type="submit">Guardar</button></form><% } %></td></tr><% } } else { %><tr><td colspan="4" class="text-secondary">Todavía no hay documentos cargados.</td></tr><% } %></tbody></table></div></div></div>
</main>
<%@ include file="/WEB-INF/jspf/pie.jspf" %>
